### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Robert42** [Robert42/gl-research-toolkit#18]
- [x] [scene loading weiter](https://github.com/Robert42/gl-research-toolkit/milestones/Loading%20scenes)
  - [x] #20
  - [x] #19
  - [x] #25
- [x] [debugging verbessern](https://github.com/Robert42/gl-research-toolkit/milestones/Debugging%20Features)
  - [x] #22
  - [x] #23
  - [x] #32
- [x] [scene loading weiter](https://github.com/Robert42/gl-research-toolkit/milestones/Loading%20scenes)
  - [x] #37
  - [x] #45 
  - [x] #33
    - [x] #46
    - [x] #39
  - [x] #9 
    - [x] #21
  - [x] #54
- [x] #63
  - [x] #30
  - [ ] #36
- [x] #35 
- [ ] [debugging verbessern](https://github.com/Robert42/gl-research-toolkit/milestones/Debugging%20Features)
  - [x] #34
  - [ ] #15
  - [x] #67 
  - [ ] #24
  - [ ] #42
  - [ ] #41
- [ ] [profiler](https://github.com/Robert42/gl-research-toolkit/milestones/Profiler)
  - [ ] #11
  - [x] #10 
- [x] alle TODOs ?
- [ ] #26
- [x] #27
- [x] #3
- [x] #28
- [ ] #29
- [x] #70
- [x] mipmaps: roughness anpassen anhand normalmap (see Listing 32 of Frostbite)
- [ ] ssao
- [x] sponza
- [ ] #43
  - [x] #44
- [x] auch image based lighting
- [ ] #76
# Distance Fields
- [x] #75
- [x] #77
- [x] #78
# issues
- [x] #68
- [ ] #73
- [x] #74
